config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :teams, only: [:index, :show]
  resources :players, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

  def self.find_all
    NbaService.find_all_players.map do |attr|
      Player.from_api(attr)
    end
  end

  def self.from_api(attr)
    where(person_id: attr[:personId]).first_or_create do |new_player|
      new_player.nba_team_id        = teams_sanitizer(attr)
      new_player.person_id          = attr[:personId]
      new_player.first_name         = attr[:firstName]
      new_player.last_name          = attr[:lastName]
      new_player.date_of_birth_utc  = attr[:dateOfBirthUTC]
      new_player.height_in_feet     = attr[:heightFeet]
      new_player.height_in_inches   = attr[:heightInches]
      new_player.weight_in_ounds    = attr[:weightPounds]
    end
  end

  def self.teams_sanitizer(attributes)
    if attributes[:teams].empty?
      "N/A"
    else
      attributes[:teams].last[:teamId]
    end
  end

  def full_name
    first_name + " " + last_name
  end
end

app/models/team.rb
class Team < ApplicationRecord

  def self.find_all
    NbaService.find_all_teams.map do |attr|
      Team.from_api(attr)
    end
  end

  def self.from_api(attr)
    where(nba_team_id: attr[:teamId]).first_or_create do |new_team|
      new_team.nba_team_id    = attr[:teamId]
      new_team.city      = attr[:city]
      new_team.full_name  = attr[:fullName]
      new_team.nickname  = attr[:nickname]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.find_all
  end

  def show
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.find_all
  end

  def show
    # @team = Team.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaData</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<% @players.each do |player| %>
  <ul>
    <li>
      <%= link_to player.full_name, player_path(player) %>
    </li>
  </ul>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "View Teams", teams_path %>
<%= link_to "View Players", players_path %>